### ISSUE TITLE
PHP 7 upload progress

### ISSUE THREAD

**Issue by bradjones1** [BradJonesLLC/docker-drupal#12]
Holding off until https://github.com/twigphp/Twig/issues/1695 is resolved re: the Twig PHP extension.

**Comment by bradjones1** [comment]
Also, uploadprogress https://bugs.php.net/bug.php?id=69242 - or, use `apcu` instead. See https://api.drupal.org/api/drupal/core!modules!file!file.install/function/file_requirements/8

**Comment by bradjones1** [comment]
And memcached needs to be compiled... https://serverpilot.io/community/articles/how-to-install-the-php-memcache-extension.html

**Comment by alloylab** [comment]
```
# compile memcached #
RUN git clone -b php7 https://github.com/php-memcached-dev/php-memcached.git /tmp/php-memcached && \
        cd /tmp/php-memcached && \
        phpize && \
        ./configure --prefix=/usr --disable-memcached-session --disable-memcached-sasl && \
        make && \
        make install && \
        echo 'extension=memcached.so' > /etc/php7/conf.d/memcached.ini && \
        rm -rf /tmp/*

# compile uploadprogress #
RUN git clone https://github.com/Jan-E/uploadprogress.git /tmp/php-uploadprogress && \
        cd /tmp/php-uploadprogress && \
        phpize && \
        ./configure --prefix=/usr && \
        make && \
        make install && \
        echo 'extension=uploadprogress.so' > /etc/php7/conf.d/uploadprogress.ini && \
        rm -rf /tmp/*
```

**Comment by bradjones1** [comment]
@alloylab Thanks... Merge requests welcome!

**Comment by bradjones1** [comment]
This is over at https://github.com/BradJonesLLC/docker-drupal/pull/15 - I'm going to rename this issue to better reflect the issue around uploadprogress and/or APCu support for the upload progress functionality. Also see https://www.drupal.org/node/2718253

**Comment by bradjones1** [comment]
Added uploadprogress in https://github.com/BradJonesLLC/docker-drupal/commit/bf7a8cd83712be03c0dd2b08801156b7df165bc0, and memcached can be added on a case-by-case basis since there is no native support in Drupal core.
