### ISSUE TITLE
post-create-project-cmd event returned with error code 1

### ISSUE THREAD

**Issue by drupler** [BradJonesLLC/docker-drupal#18]
While creating project by mentioned command I got this error in the end.

`Script sh scripts/composer/install.sh handling the post-create-project-cmd event returned with error code 1`

**Comment by bradjones1** [comment]
It is possible you don't have one of the required commands present in your environment, e.g., `sed`.

This is a rather "soft" error, in that you can just go in and try to run the script yourself, or determine where in the script it failed by a little trial-and-error. Regardless, just tested this on Ubuntu and it worked OK. What platform are you on?

See https://github.com/BradJonesLLC/docker-drupal/blob/7d82d36911444d00ec9c6abf4e40ed97c34b0f97/scripts/composer/install.sh

**Comment by bradjones1** [comment]
Reporting party not responding; closing.
